// <auto-generated />
namespace CQA.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddedConcepts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedConcepts));
        
        string IMigrationMetadata.Id
        {
            get { return "201402042023253_AddedConcepts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
