// <auto-generated />
namespace CQA.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class removed_UserId_from_Question : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removed_UserId_from_Question));
        
        string IMigrationMetadata.Id
        {
            get { return "201405181750008_removed_UserId_from_Question"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
